### Admin Login
POST https://capstone-backend-tx3g.onrender.com/auth-api/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "abcdef"
}

###

### Get all users
GET https://capstone-backend-tx3g.onrender.com/admin-api/users

###

###  Get all authors
GET https://capstone-backend-tx3g.onrender.com/admin-api/authors

###

### Block user
PUT https://capstone-backend-tx3g.onrender.com/admin-api/user/block/69dcd419008c306291a55c5a

###

### Activate user
PUT https://capstone-backend-tx3g.onrender.com/admin-api/user/activate/69dcd419008c306291a55c5a

###

### Block author
PUT https://capstone-backend-tx3g.onrender.com/admin-api/author/block/AUTHOR_ID

###

### Activate author
PUT https://capstone-backend-tx3g.onrender.com/admin-api/author/activate/AUTHOR_ID