###register user
POST http://capstone-backend-tx3g.onrender.com/auth-api/users
Content-Type: application/json

{
    "firstName":"kalpana",
    "lastName":"raj",
    "email":"raj@gmail.com",
    "password":"123456",
    "role":"USER",
    "profileImageUrl":"image"
    }


###authentication
POST http://capstone-backend-tx3g.onrender.com/auth-api/login
Content-Type: application/json

{
    
    "email":"gcsr@gmail.com",
    "password":"abcd"
    }
###
GET http://capstone-backend-tx3g.onrender.com/auth-api/logout

### read articles of all authors
GET http://capstone-backend-tx3g.onrender.com/user-api/article

###add comment by user to an article
PUT http://capstone-backend-tx3g.onrender.com/user-api/article
Content-Type: application/json

{
    "articleId":"",
    "comment":"this is amazing"
}

###change password
PUT http://capstone-backend-tx3g.onrender.com/auth/password
Content-Type: application/json

{
    "currentPassword":"abcd",
    "newPassword":"dcba"
}

